### PR TITLE
Create model for products and tests for products

### PR DESCRIPTION
**Pull request by zqf0722**
Create model for the products. 

Added needed unit tests for the model methods.

The schema for products:

```
{
      userID: user_id1          String       foreign key
      productID: product_id1         String        key
      productQuantity: product_quantity1        Float
      productName: product_name1       String
      price: price1             Float
      purchaseTime: purchase_time1         Date
}
```

### CODE REVIEW

**Comment by Greatpep** [comment]
Looks good to me! Some small suggestions: The productID should be marked as the primary key and if would be better if the type of userId and productId be auto incremental BIGINT.

**Comment by Yuhao-Fan** [comment]
Will you get the same error from nosetests
devops@nyu:/app$ nosetests
(psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "shopcarts"

[SQL: 
CREATE TABLE products (
        id SERIAL NOT NULL, 
        "userId" VARCHAR(63) NOT NULL, 
        "productId" VARCHAR(63) NOT NULL, 
        name VARCHAR(63) NOT NULL, 
        quantity FLOAT NOT NULL, 
        price FLOAT NOT NULL, 
        time DATE NOT NULL, 
        PRIMARY KEY (id), 
        FOREIGN KEY("userId") REFERENCES shopcarts ("userId")
)

]
(Background on this error at: https://sqlalche.me/e/14/f405): Cannot continue

**Comment by zqf0722** [comment]
> Will you get the same error from nosetests? devops@nyu:/app$ nosetests (psycopg2.errors.InvalidForeignKey) there is no unique constraint matching given keys for referenced table "shopcarts"
> 
> [SQL: CREATE TABLE products ( id SERIAL NOT NULL, "userId" VARCHAR(63) NOT NULL, "productId" VARCHAR(63) NOT NULL, name VARCHAR(63) NOT NULL, quantity FLOAT NOT NULL, price FLOAT NOT NULL, time DATE NOT NULL, PRIMARY KEY (id), FOREIGN KEY("userId") REFERENCES shopcarts ("userId") )
> 
> ] (Background on this error at: https://sqlalche.me/e/14/f405): Cannot continue

No I'm not getting thsi error. I passed all the nosetests locally, so I don't know what's the issue.

**Comment by zqf0722** [comment]
> Looks good to me! Some small suggestions: The productID should be marked as the primary key and if would be better if the type of userId and productId be auto incremental BIGINT.

Please do not merge the PR after your review. Just approve the PR review, because there might be some issues with other reviewers. Thanks.

**Pull request merged**
