### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by Greatpep**
update requirements

### CODE REVIEW

**Comment by zqf0722** [comment]
Don't open another PR to fix problems of another PR. Just push your code to the branch of the other PR

**Comment by Greatpep** [comment]
> Don't open another PR to fix problems of another PR. Just push your code to the branch of the other PR

the branch is protected and I can change it only create a new branch before merging into the main

**Comment by zqf0722** [comment]
> > Don't open another PR to fix problems of another PR. Just push your code to the branch of the other PR
> 
> the branch is protected and I can change it only create a new branch before merging into the main

This may because you give the branch a name like "master" or "main". It happens to @Yvonne98XU too. Try use a different branch name instead of "master" or "main".

**Comment by zqf0722** [comment]
> > Don't open another PR to fix problems of another PR. Just push your code to the branch of the other PR
> 
> the branch is protected and I can change it only create a new branch before merging into the main

You can push to your branch without permission. Only the main branch is protected.

**Comment by Greatpep** [comment]
> 

the branch I try to change is CI_setup and you can see from the merge request

**Pull request closed without merging**
