### PR TITLE
Ci setup

### PR DESCRIPTION
**Pull request by Greatpep**
commit workflow comfig

### CODE REVIEW

**Review by Yvonne98XU — CHANGES_REQUESTED** [review]
Something seems wrong with the dependency installation.

**Comment by zqf0722** [comment]
The CIO build fails. Please see what the problem is. @Greatpep

**Comment by zqf0722** [comment]
Also, please link those 2 PR to the issue you create and assign the issue to yourself.

**Review by Yvonne98XU — APPROVED** [review]

**Comment by Yvonne98XU** [comment]
Fix the bugs, already merged.

**Pull request merged**
